---
- name: Copy Interface Configuration File
  template:
    src: roles/templates/server_interface_template.j2
    dest: /etc/network/interfaces

- name: Restart Servers
  shell: sleep 2 && shutdown -r now
  async: 1
  poll: 0
  ignore_errors: true

- name: waiting for servers to come back
  wait_for_connection:
    host: "{{ ansible_hostname }}"
    delay: 15

...
